INSERT INTO tb_classe(name) VALUES ('FACILITADOR DE EXTRUSORA');
INSERT INTO tb_classe(name) VALUES ('FACILITADOR DE TERMOFORMADORA');
INSERT INTO tb_classe(name) VALUES ('OPERADORA DE MAQUINA');
INSERT INTO tb_classe(name) VALUES ('LIDER DE EQUIPE');
INSERT INTO tb_classe(name) VALUES ('MECÂNICO');
INSERT INTO tb_classe(name) VALUES ('ELETRICISTA');