INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE EXTRUSORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE TERMOFORMADORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('OPERADORA DE MAQUINA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('LIDER DE EQUIPE', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('MECÂNICO', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRICISTA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE EXTRUSORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE TERMOFORMADORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('OPERADORA DE MAQUINA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('LIDER DE EQUIPE', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('MECÂNICO', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRICISTA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE EXTRUSORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE TERMOFORMADORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('OPERADORA DE MAQUINA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('LIDER DE EQUIPE', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('MECÂNICO', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRICISTA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE EXTRUSORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE TERMOFORMADORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('OPERADORA DE MAQUINA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('LIDER DE EQUIPE', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('MECÂNICO', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRICISTA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE EXTRUSORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE TERMOFORMADORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('OPERADORA DE MAQUINA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('LIDER DE EQUIPE', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('MECÂNICO', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRICISTA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE EXTRUSORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE TERMOFORMADORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('OPERADORA DE MAQUINA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('LIDER DE EQUIPE', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('MECÂNICO', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRICISTA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE EXTRUSORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE TERMOFORMADORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('OPERADORA DE MAQUINA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('LIDER DE EQUIPE', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('MECÂNICO', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRICISTA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE EXTRUSORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE TERMOFORMADORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('OPERADORA DE MAQUINA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('LIDER DE EQUIPE', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('MECÂNICO', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRICISTA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE EXTRUSORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('FACILITADOR DE TERMOFORMADORA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('OPERADORA DE MAQUINA', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('LIDER DE EQUIPE', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('MECÂNICO', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('ELETRICISTA', NOW());